language: cpp
compiler:
  - gcc
  - clang
before_install:
  - if [ $CC = "clang" ]; then export PATH="/usr/bin/:$PATH"; sudo sh -c 'echo "deb http://ppa.launchpad.net/eudoxos/llvm-3.1/ubuntu precise main" >> /etc/apt/sources.list'; sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 92DE8183; sudo apt-get update; sudo apt-get install llvm-3.1; sudo apt-get install clang; fi
  - sudo apt-get install libirrlicht-dev cmake libpng12-dev libbz2-dev libjpeg8-dev libgl1-mesa-dev libxxf86vm-dev libgl1-mesa-dev
script: cmake . && make
notifications:
  email: false

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "c9fu1SYadL7BRWTvz1cpENNWi94tBYaMeu4iqEBahiiyyPIr/77FZLqPw6q8Jv8slcEMm2axr2+v6XH3xQrW1bvmEFOhr9oRZRJ/QB8YbdbjbNYUs5WpH4cFinUF1DTCebltxFTyY7srrw0S+yIQUSILB99Cfor8bWr5WVVmUwI="

addons:
  coverity_scan:
    project:
      name: "rubenwardy/NodeBoxEditor"
      description: "NBE"
    notification_email: rubenwardy@gmail.com
    build_command_prepend: "make clean"
    build_command:   "cmake . && make -j3"
    branch_pattern: coverity_scan
